---
- hosts: webservers
  become: true
  vars_files:
    - ansible_vars_file.yml

  tasks:
    - name: Stop any running container
      command: docker stop appContainer
      ignore_errors: yes

    - name: Remove stopped container
      command: docker rm appContainer
      ignore_errors: yes

    - name: Remove old Docker image
      command: docker rmi {{ NEXUS_IP }}/petclinicapps:latest
      ignore_errors: yes

    - name: Log in to Nexus and run new Docker container
      shell: |
        docker login --username=admin --password=admin123 {{ NEXUS_IP }}
        docker pull {{ NEXUS_IP }}/petclinicapps:latest
        docker run -it -d --name appContainer -p 8080:8080 {{ NEXUS_IP }}/petclinicapps:latest
